package io.github.cl0ura.hypericonpack.systemtheme

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.pm.ActivityInfo
import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.drawable.AdaptiveIconDrawable
import android.graphics.drawable.Drawable
import android.os.Build
import android.util.Log
import io.github.cl0ura.hypericonpack.config.IconPackConfig
import io.github.cl0ura.hypericonpack.iconpack.ParsedIconPack
import io.github.cl0ura.hypericonpack.ui.RootAccess
import java.io.BufferedOutputStream
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.security.MessageDigest
import java.util.Locale
import java.util.Calendar
import java.util.zip.ZipEntry
import java.util.zip.Deflater
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream

/**
 * Converts the public, de-facto standard appfilter.xml contract into the
 * exact icon archive layout consumed by HyperOS ThemeResourcesSystem.
 *
 * HyperOS opens /data/system/theme/icons as a normal ZIP and asks it for
 * entries such as:
 *
 *   res/drawable-xxhdpi/com.example.MainActivity.png
 *   res/drawable-xxhdpi/com.example#ExternalActivity.png
 *
 * The archive is intentionally generated before any Root operation.  This
 * keeps conversion inspectable and makes installation a separate, reversible
 * step.
 */
internal object HyperOsIconArchiveConverter {
    const val ORIGINAL_ICON_PACKAGE = "io.github.cl0ura.hypericonpack.source.original"
    const val ORIGINAL_ICON_LABEL = "本机原始图标"

    /** Kept only to recognise archives generated by pre-cache module builds. */
    const val ARCHIVE_FILE_NAME = "hypericonpack-icons.zip"
    private const val ARCHIVE_DIRECTORY = "hyperos-theme"
    private const val ARCHIVE_CACHE_DIRECTORY = "archives"
    private const val ARCHIVE_FILE_PREFIX = "icons-"
    private const val DYNAMIC_ARCHIVE_SUFFIX = "-dynamicicons.zip"
    /**
     * Version 17 retains the icon pack's complete appfilter contract, then
     * adds precise resources for desktop-launchable components and every
     * installed package.  This deliberately avoids baking thousands of
     * internal Activities into one archive: HyperOS can stop resolving icons
     * reliably when its private theme ZIP grows excessively large.  For
     * Global Monet, an application's API 33+ native monochrome layer is used
     * only when the selected icon pack has no usable mapping for that app.
     */
    private const val CURRENT_FORMAT_VERSION = 29
    private const val TARGET_DENSITY_DIRECTORY = "res/drawable-xxhdpi"
    private const val METADATA_ENTRY = "META-INF/hypericonpack-conversion.properties"
    private const val TRANSFORM_CONFIG_ENTRY = "transform_config.xml"
    private const val DEFAULT_RENDERING = "original"
    private const val GLOBAL_MONET_RENDERING = "global_monet_v18"
    private const val GLOBAL_MONET_RENDERING_PREFIX = "global_monet_v"
    private const val ALL_APPLICATIONS_SCOPE = "all"
    private const val SCOPE_FINGERPRINT_LENGTH = 20
    // A xxhdpi launcher icon is normally displayed at roughly 144 px on the
    // target device.  256 px leaves comfortable downsampling headroom while
    // reducing Monet's per-pixel work and temporary bitmap allocation by more
    // than half compared with the old 384 px output.
    private const val RENDER_SIZE_PX = 256
    private const val PROGRESS_REPORT_INTERVAL = 12
    private const val DYNAMIC_ICON_SIZE_PX = 256

    enum class ConversionPhase {
        PARSING,
        EXPLICIT_MAPPINGS,
        FALLBACK_ACTIVITIES,
        VALIDATING,
        COMPLETED,
    }

    /** A thread-safe, value-only snapshot delivered by [convert]. */
    data class ConversionProgress(
        val phase: ConversionPhase,
        val completed: Int,
        val total: Int,
        val explicitCompleted: Int = 0,
        val explicitTotal: Int = 0,
        val fallbackCompleted: Int = 0,
        val fallbackTotal: Int = 0,
    ) {
        val fraction: Float
            get() = if (total <= 0) 0f else completed.toFloat() / total.toFloat()
    }

    data class Result(
        val archive: File,
        val requestedExplicitMappings: Int,
        val convertedExplicitMappings: Int,
        val fallbackCandidates: Int,
        val convertedFallbackMappings: Int,
        val convertedPackageDefaults: Int,
        val nativeMonochromeIcons: Int,
        val skippedMappings: Int,
        val archiveSha256: String,
        val dynamicArchive: File?,
    ) {
        val convertedMappings: Int
            get() = convertedExplicitMappings + convertedFallbackMappings
    }

    /** Lightweight local state used only to make the settings UI truthful. */
    data class ExistingArchiveInfo(
        val archive: File,
        val iconPackPackage: String?,
        val fallbackScaleMultiplier: Float?,
        val globalMonetIcons: Boolean,
        val monetCustomColors: Boolean,
        val monetBackgroundColor: Int,
        val monetForegroundColor: Int,
        val applicationScopeFingerprint: String,
        val formatVersion: Int?,
    ) {
        val isCurrentFormat: Boolean
            get() = formatVersion == CURRENT_FORMAT_VERSION
    }

    /**
     * Android's native themed-icon layer supplies a semantic foreground only.
     * Keep its original adaptive icon alongside it so Monet can retain the
     * source icon's visible silhouette instead of imposing a circular frame.
     */
    private data class NativeMonochromeSource(
        val glyph: Drawable,
        val silhouette: Drawable,
        // Semantic monochrome resources can be broken by an OEM. Keep a
        // drawable that can always be written as a recognisable PNG instead
        // of treating a solid Monet block as a successful fallback.
        val recoveryDrawable: Drawable,
    )

    fun isOriginalIconSource(packageName: String?): Boolean = packageName == ORIGINAL_ICON_PACKAGE

    fun sourceLabel(packageName: String?): String = when {
        packageName == null -> "未选择图标来源"
        isOriginalIconSource(packageName) -> ORIGINAL_ICON_LABEL
        else -> packageName
    }

    /** Resolves the user-facing icon-pack application name when installed. */
    fun sourceLabel(context: Context, packageName: String?): String {
        if (packageName == null || isOriginalIconSource(packageName)) return sourceLabel(packageName)
        return runCatching {
            val info = context.packageManager.getApplicationInfo(
                packageName,
                PackageManager.MATCH_DISABLED_COMPONENTS,
            )
            context.packageManager.getApplicationLabel(info).toString().ifBlank { packageName }
        }.getOrDefault(packageName)
    }

    /**
     * Produces a validated ZIP in the app's external-files directory.  Root
     * can read that directory on stock Android, while ordinary apps cannot
     * modify the result without the module app's storage access.
     */
    fun convert(
        context: Context,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean = false,
        monetCustomColors: Boolean = false,
        monetBackgroundColor: Int = IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
        monetForegroundColor: Int = IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
        includeInstalledAppFallbacks: Boolean,
        onProgress: ((ConversionProgress) -> Unit)? = null,
    ): Result {
        require(iconPackPackage.isNotBlank()) { "请先选择一个图标来源" }

        onProgress?.invoke(
            ConversionProgress(
                phase = ConversionPhase.PARSING,
                completed = 0,
                total = 0,
            ),
        )
        var parseFailure: Throwable? = null
        val pack = if (isOriginalIconSource(iconPackPackage)) {
            null
        } else {
            ParsedIconPack.load(context, iconPackPackage) { parseFailure = it }
                ?: throw IllegalStateException(
                    "无法读取 $iconPackPackage 的 appfilter.xml",
                    parseFailure,
                )
        }
        val allMappings = pack?.explicitMappings().orEmpty()
        if (pack != null) {
            require(allMappings.isNotEmpty()) { "图标包不含可转换的 ComponentInfo 图标映射" }
        }
        val scopeFingerprint = applicationScopeFingerprint(context)
        // Convert the icon pack's full public contract first. HyperOS vendor
        // aliases and non-launcher surfaces can request component names that
        // are not visible through ACTION_MAIN/CATEGORY_LAUNCHER, so filtering
        // appfilter by currently launchable activities makes coverage worse.
        val installedApplications = if (includeInstalledAppFallbacks) {
            installedApplications(context)
        } else {
            emptyList()
        }
        val installedPackageNames = installedApplications.mapTo(HashSet()) { it.packageName }
        // HyperOS uses the generated PNG as-is. Keep an OEM adaptive mask so
        // legacy original icons retain the same rounded system footprint they
        // would receive from the regular launcher pipeline.
        val systemAdaptiveMask = resolveSystemAdaptiveMask(context, installedApplications)
        val fallbackActivities = if (includeInstalledAppFallbacks) {
            // The complete appfilter mapping is already written above. For
            // installed applications not represented by it, add only actual
            // desktop launch targets; emitting every internal Activity bloats
            // an archive from ~8k to ~29k entries on this device and makes
            // HyperOS skip theme lookups under memory/ZIP pressure.
            launchableActivities(context).filter { info -> info.packageName in installedPackageNames }
        } else {
            emptyList()
        }
        val mappings = if (pack == null) {
            emptyList()
        } else {
            allMappings
        }
        val fallbackWorkTotal = fallbackActivities.size + installedApplications.size
        val progressTotal = mappings.size + fallbackWorkTotal
        onProgress?.invoke(
            ConversionProgress(
                phase = ConversionPhase.EXPLICIT_MAPPINGS,
                completed = 0,
                total = progressTotal,
                explicitTotal = mappings.size,
                fallbackTotal = fallbackWorkTotal,
            ),
        )

        // Every package/scale pair gets its own durable archive. Changing to a
        // previously converted pack is therefore only an install operation;
        // no full all-app render is repeated unless the user explicitly asks
        // to refresh it.
        val archive = archiveFile(
            context = context,
            iconPackPackage = iconPackPackage,
            fallbackScaleMultiplier = fallbackScaleMultiplier,
            globalMonetIcons = globalMonetIcons,
            monetCustomColors = monetCustomColors,
            monetBackgroundColor = monetBackgroundColor,
            monetForegroundColor = monetForegroundColor,
            applicationScopeFingerprint = scopeFingerprint,
            createDirectory = true,
        )
        val temporaryArchive = File(archive.parentFile, "${archive.name}.new")
        // FileOutputStream truncates a previous interrupted temporary result,
        // so a stale partial archive is never installed as a final artifact.

        var explicitConverted = 0
        val fallbackCandidates = installedApplications.size
        var fallbackConverted = 0
        var packageDefaultsConverted = 0
        var skipped = 0
        var monetCompatibilityRenders = 0
        var monetEmergencyFallbacks = 0
        var nativeMonochromeIcons = 0
        val entryNames = HashSet<String>()
        val successfullyConvertedComponents = HashSet<ComponentName>()
        // Every installed package receives one visual fallback.  Activity
        // aliases must all get their own ZIP entry for HyperOS lookup, but
        // rendering a separate identical Monet bitmap for each alias made a
        // full conversion needlessly take many minutes.  This cache holds at
        // most one compressed 256px PNG per installed package.
        val packageFallbackPngs = HashMap<String, ByteArray?>()
        // The same application icon can appear under multiple appfilter
        // components. Cache the resolved monochrome Drawable so the
        // conversion does not repeat PackageManager resource lookups for
        // every alias in a large icon pack. A null value is cached as well:
        // it means this app simply has no native themed-icon layer.
        val nativeMonochromeByPackage = HashMap<String, NativeMonochromeSource?>()
        val nativeMonochromeByComponent = HashMap<ComponentName, NativeMonochromeSource?>()
        val installedApplicationsByPackage = installedApplications.associateBy(ApplicationInfo::packageName)
        val launchableActivitiesByComponent = fallbackActivities
            .mapNotNull { info -> componentName(info)?.let { component -> component to info } }
            .toMap()
        val globalMonetPalette = if (globalMonetIcons) {
            SystemMonetIconPalette.global(
                context = context,
                useCustomColors = monetCustomColors,
                backgroundColor = monetBackgroundColor,
                foregroundColor = monetForegroundColor,
            )
        } else {
            null
        }
        try {
            ZipOutputStream(BufferedOutputStream(FileOutputStream(temporaryArchive))).use { zip ->
                // PNG already performs lossless DEFLATE internally. Running
                // the ZIP's default maximum compressor over thousands of PNGs
                // barely changes archive size but consumes a large share of
                // conversion time.
                zip.setLevel(Deflater.NO_COMPRESSION)
                writeArchiveMetadata(
                    zip = zip,
                    iconPackPackage = iconPackPackage,
                    fallbackScaleMultiplier = fallbackScaleMultiplier,
                    globalMonetIcons = globalMonetIcons,
                    monetCustomColors = monetCustomColors,
                    monetBackgroundColor = monetBackgroundColor,
                    monetForegroundColor = monetForegroundColor,
                    applicationScopeFingerprint = scopeFingerprint,
                )
                writeTransformConfig(zip, useDynamicIcon = false)
                fun renderDrawable(
                    drawable: Drawable,
                    nativeMonochrome: NativeMonochromeSource? = null,
                ): ByteArray? {
                    return try {
                        // Render first. If a malformed third-party Drawable
                        // throws after ZipOutputStream.putNextEntry(), a zero
                        // byte ZIP member remains and later archive validation
                        // fails even though the rest of conversion succeeded.
                        // Buffering one 384 px PNG avoids that poisoned entry.
                        val png = ByteArrayOutputStream()
                        if (globalMonetPalette != null) {
                            // A bad third-party Drawable must never remove the
                            // associated component from a global Monet archive.
                            // If its pixels cannot be rendered, retain a
                            // shaped Monet resource rather than falling back
                            // to HyperOS's original coloured app icon.
                            val monetRendered = runCatching {
                                if (nativeMonochrome != null) {
                                    GlobalMonetIconRenderer.renderNativeMonochrome(
                                        glyph = nativeMonochrome.glyph,
                                        silhouette = nativeMonochrome.silhouette,
                                        palette = globalMonetPalette,
                                        size = RENDER_SIZE_PX,
                                        output = png,
                                    )
                                } else {
                                    GlobalMonetIconRenderer.render(
                                        drawable = drawable,
                                        palette = globalMonetPalette,
                                        size = RENDER_SIZE_PX,
                                        output = png,
                                    )
                                }
                            }.isSuccess
                            if (!monetRendered) {
                                png.reset()
                                val compatibilityRendered = runCatching {
                                    GlobalMonetIconRenderer.renderSimplified(
                                        // A rejected native monochrome layer
                                        // must fall back to the complete source
                                        // artwork. Recolouring the silhouette
                                        // alone produces a blank colour tile.
                                        drawable = nativeMonochrome?.recoveryDrawable ?: drawable,
                                        palette = globalMonetPalette,
                                        size = RENDER_SIZE_PX,
                                        output = png,
                                    )
                                }.isSuccess
                                if (compatibilityRendered) {
                                    monetCompatibilityRenders++
                                } else {
                                    // A high-fidelity renderer can reject an
                                    // OEM Drawable for reasons unrelated to
                                    // its pixels. Before conceding coloured
                                    // output, use the deterministic two-tone
                                    // renderer: if the source can be drawn it
                                    // will remain a real Monet icon, never an
                                    // empty colour block or a large patch of
                                    // original-colour apps.
                                    png.reset()
                                    val guaranteedRendered = runCatching {
                                        GlobalMonetIconRenderer.renderGuaranteed(
                                            drawable = nativeMonochrome?.recoveryDrawable ?: drawable,
                                            palette = globalMonetPalette,
                                            size = RENDER_SIZE_PX,
                                            output = png,
                                        )
                                    }.isSuccess
                                    if (!guaranteedRendered) {
                                        monetEmergencyFallbacks++
                                        return null
                                    }
                                }
                            }
                        } else {
                            renderDrawableAsPng(drawable, png)
                        }
                        png.toByteArray()
                    } catch (_: Throwable) {
                        null
                    }
                }

                fun appendPng(entryName: String, png: ByteArray): Boolean {
                    return try {
                        zip.putNextEntry(ZipEntry(entryName))
                        zip.write(png)
                        zip.closeEntry()
                        true
                    } catch (_: Throwable) {
                        // Some commercial packs contain stale resources. No
                        // ZIP member was opened before rendering completed,
                        // so the validated archive can safely retain all
                        // other applications.
                        runCatching { zip.closeEntry() }
                        false
                    }
                }

                fun appendDrawable(
                    entryName: String,
                    drawable: Drawable,
                    nativeMonochrome: NativeMonochromeSource? = null,
                ): Boolean = renderDrawable(drawable, nativeMonochrome)
                    ?.let { png -> appendPng(entryName, png) }
                    ?: false

                fun nativeMonochromeForPackage(
                    packageName: String,
                    applicationInfo: ApplicationInfo?,
                ): NativeMonochromeSource? {
                    if (!globalMonetIcons || applicationInfo == null) return null
                    if (nativeMonochromeByPackage.containsKey(packageName)) {
                        return nativeMonochromeByPackage[packageName]
                    }
                    return nativeMonochromeSource(rawApplicationIcon(context, applicationInfo))
                        .also { nativeMonochromeByPackage[packageName] = it }
                }

                fun nativeMonochromeForComponent(component: ComponentName): NativeMonochromeSource? {
                    if (!globalMonetIcons) return null
                    if (nativeMonochromeByComponent.containsKey(component)) {
                        return nativeMonochromeByComponent[component]
                    }
                    val activityInfo = launchableActivitiesByComponent[component]
                    val applicationInfo = installedApplicationsByPackage[component.packageName]
                    // Activity icons may intentionally differ from the app's
                    // default icon. Prefer their native monochrome layer, but
                    // always fall back to the application's declared layer.
                    val layer = activityInfo?.let { info ->
                        nativeMonochromeSource(rawActivityIcon(context, info))
                    } ?: nativeMonochromeForPackage(component.packageName, applicationInfo)
                    nativeMonochromeByComponent[component] = layer
                    return layer
                }

                fun packageFallbackPng(applicationInfo: ApplicationInfo, packageName: String): ByteArray? {
                    if (packageFallbackPngs.containsKey(packageName)) {
                        return packageFallbackPngs[packageName]
                    }
                    // For an unmapped package, all Activity/alias entries use
                    // the package icon as their common visual fallback. This
                    // is both consistent on the desktop and lets one rendered
                    // PNG populate all component names for that package.
                    // A valid appfilter resource is always the user's chosen
                    // icon-pack artwork, so it wins even in Global Monet
                    // mode. Native monochrome is deliberately an unmapped-app
                    // enhancement rather than a replacement for an icon pack.
                    val iconPackDrawable = mappedPackageDrawable(
                        pack = pack,
                        packageName = packageName,
                        prepareForMonet = globalMonetIcons,
                    )
                    val rawIcon = rawApplicationIcon(context, applicationInfo)
                    // Build the icon-pack/System fallback first. When an app
                    // has Android's native monochrome glyph, that glyph is
                    // rendered *inside this prepared silhouette*. Previously
                    // we used the raw AdaptiveIconDrawable as the silhouette
                    // here, bypassing Pure's circular iconmask for every
                    // unmapped app and making a large part of the pack square
                    // as soon as Global Monet was enabled.
                    val preparedFallback = bestPackageDrawable(
                        pack = pack,
                        packageName = packageName,
                        rawIcon = rawIcon,
                        fallbackComponent = ComponentName(packageName, packageName),
                        fallbackScaleMultiplier = fallbackScaleMultiplier,
                        systemAdaptiveMask = systemAdaptiveMask,
                        prepareForMonet = globalMonetIcons,
                    )
                    val rawNativeMonochrome = if (iconPackDrawable == null) {
                        nativeMonochromeForPackage(packageName, applicationInfo)
                    } else {
                        null
                    }
                    val nativeMonochrome = rawNativeMonochrome?.let { native ->
                        preparedFallback?.let { silhouette ->
                            native.copy(silhouette = silhouette, recoveryDrawable = silhouette)
                        } ?: native
                    }
                    val drawable = iconPackDrawable
                        ?: nativeMonochrome?.glyph
                        ?: preparedFallback
                    if (nativeMonochrome != null) {
                        nativeMonochromeIcons++
                    }
                    val png = drawable?.let { renderDrawable(it, nativeMonochrome) }
                    packageFallbackPngs[packageName] = png
                    return png
                }

                if (pack != null) {
                    mappings.forEachIndexed { index, mapping ->
                        val entryName = archiveEntryName(mapping.component)
                        if (entryNames.contains(entryName)) {
                            // HyperOS resolves by Component name.  Duplicate XML
                            // items for the same component are ambiguous; retain
                            // the first one, matching the parser's map semantics.
                            skipped++
                        } else {
                            val iconPackDrawable = if (globalMonetIcons) {
                                pack.loadMappedDrawableForMonet(mapping.drawableName, mapping.component)
                            } else {
                                pack.loadMappedDrawable(mapping.drawableName)
                            }
                            // Some packs retain appfilter rows whose drawable
                            // was removed or placed in an unavailable split.
                            // Treat that as an unmapped installed app and use
                            // the pack's public iconback/iconmask fallback
                            // before considering the app's own monochrome
                            // layer. This keeps one broken row from becoming a
                            // square icon inside an otherwise circular pack.
                            val applicationInfo = installedApplicationsByPackage[mapping.component.packageName]
                            val activityInfo = launchableActivitiesByComponent[mapping.component]
                            val rawIcon = activityInfo?.let { rawActivityIcon(context, it) }
                                ?: applicationInfo?.let { rawApplicationIcon(context, it) }
                            val preparedFallback = if (iconPackDrawable == null && rawIcon != null) {
                                bestPackageDrawable(
                                    pack = pack,
                                    packageName = mapping.component.packageName,
                                    rawIcon = rawIcon,
                                    fallbackComponent = mapping.component,
                                    fallbackScaleMultiplier = fallbackScaleMultiplier,
                                    systemAdaptiveMask = systemAdaptiveMask,
                                    prepareForMonet = globalMonetIcons,
                                )
                            } else {
                                null
                            }
                            val rawNativeMonochrome = if (iconPackDrawable == null) {
                                nativeMonochromeForComponent(mapping.component)
                            } else {
                                null
                            }
                            val nativeMonochrome = rawNativeMonochrome?.let { native ->
                                preparedFallback?.let { silhouette ->
                                    native.copy(silhouette = silhouette, recoveryDrawable = silhouette)
                                } ?: native
                            }
                            val drawable = iconPackDrawable ?: nativeMonochrome?.glyph ?: preparedFallback
                            if (drawable == null) {
                                skipped++
                            } else if (appendDrawable(entryName, drawable, nativeMonochrome)) {
                                entryNames.add(entryName)
                                successfullyConvertedComponents.add(mapping.component)
                                explicitConverted++
                                if (nativeMonochrome != null) nativeMonochromeIcons++
                            } else {
                                skipped++
                            }
                        }
                        reportProgress(
                            callback = onProgress,
                            phase = ConversionPhase.EXPLICIT_MAPPINGS,
                            phaseCompleted = index + 1,
                            phaseTotal = mappings.size,
                            totalCompleted = index + 1,
                            total = progressTotal,
                            explicitCompleted = index + 1,
                            explicitTotal = mappings.size,
                            fallbackCompleted = 0,
                            fallbackTotal = fallbackWorkTotal,
                            force = index + 1 == mappings.size,
                        )
                    }
                }

                // Write exact resources for desktop launch targets. Package
                // resources below cover Settings, SystemUI and non-launcher
                // system surfaces without turning the archive into a copy of
                // every app's internal navigation Activity.
                fallbackActivities.forEachIndexed { index, activityInfo ->
                    val component = componentName(activityInfo)
                    if (component != null && component !in successfullyConvertedComponents) {
                        val entryName = archiveEntryName(component)
                        if (!entryNames.contains(entryName)) {
                            val png = packageFallbackPng(
                                applicationInfo = activityInfo.applicationInfo,
                                packageName = component.packageName,
                            )
                            if (png == null) {
                                skipped++
                            } else if (appendPng(entryName, png)) {
                                entryNames.add(entryName)
                                fallbackConverted++
                            } else {
                                skipped++
                            }
                        }
                    }
                    reportProgress(
                        callback = onProgress,
                        phase = ConversionPhase.FALLBACK_ACTIVITIES,
                        phaseCompleted = index + 1,
                        phaseTotal = fallbackWorkTotal,
                        totalCompleted = mappings.size + index + 1,
                        total = progressTotal,
                        explicitCompleted = mappings.size,
                        explicitTotal = mappings.size,
                        fallbackCompleted = index + 1,
                        fallbackTotal = fallbackWorkTotal,
                        force = index + 1 == fallbackWorkTotal,
                    )
                }

                // All installed packages includes system applications without
                // a MAIN/LAUNCHER activity.  Their package-level icon is what
                // Settings and many HyperOS system surfaces resolve.
                installedApplications.forEachIndexed { index, applicationInfo ->
                    val packageName = applicationInfo.packageName
                    val entryName = packageArchiveEntryName(packageName)
                    if (!entryNames.contains(entryName)) {
                        val png = packageFallbackPng(applicationInfo, packageName)
                        if (png == null) {
                            skipped++
                        } else if (appendPng(entryName, png)) {
                            entryNames.add(entryName)
                            packageDefaultsConverted++
                        } else {
                            skipped++
                        }
                    }
                    val completed = fallbackActivities.size + index + 1
                    reportProgress(
                        callback = onProgress,
                        phase = ConversionPhase.FALLBACK_ACTIVITIES,
                        phaseCompleted = completed,
                        phaseTotal = fallbackWorkTotal,
                        totalCompleted = mappings.size + completed,
                        total = progressTotal,
                        explicitCompleted = mappings.size,
                        explicitTotal = mappings.size,
                        fallbackCompleted = completed,
                        fallbackTotal = fallbackWorkTotal,
                        force = index + 1 == installedApplications.size,
                    )
                }
            }
            val totalConverted = explicitConverted + fallbackConverted
            require(totalConverted + packageDefaultsConverted > 0) { "所选应用的图标资源均无法渲染为 PNG" }
            onProgress?.invoke(
                ConversionProgress(
                    phase = ConversionPhase.VALIDATING,
                    completed = progressTotal,
                    total = progressTotal,
                    explicitCompleted = mappings.size,
                    explicitTotal = mappings.size,
                    fallbackCompleted = fallbackWorkTotal,
                    fallbackTotal = fallbackWorkTotal,
                ),
            )
            validateArchive(temporaryArchive, totalConverted + packageDefaultsConverted)
            if (archive.exists() && !archive.delete()) {
                throw IllegalStateException("无法替换旧的待应用主题归档")
            }
            if (!temporaryArchive.renameTo(archive)) {
                throw IllegalStateException("无法完成主题归档写入")
            }
        } catch (throwable: Throwable) {
            // Do not touch a previously successful final archive if this
            // conversion fails.  The .new file is deliberately ignored by
            // the Root installer and may be overwritten on the next attempt.
            throw throwable
        }

        val generatedDynamicArchive = generateDynamicCalendarArchive(
            pack = pack,
            installedPackageNames = installedPackageNames,
            launchableActivities = fallbackActivities,
            iconArchive = archive,
            globalMonetPalette = globalMonetPalette,
            fallbackScaleMultiplier = fallbackScaleMultiplier,
        )
        // HyperOS checks layer_animating_icons before classic animating_icons
        // whenever UseDynamicIcon=true.  The stock theme already contains
        // adaptive calendar trees, which forces square backgrounds even when a
        // pack PNG is circular.  Embed only the classic MAML tree into the main
        // icons archive and keep dynamicicons disabled; this makes the normal
        // IconCustomizer lookup select our dated PNGs without an adaptive mask.
        if (generatedDynamicArchive?.isFile == true) {
            embedClassicDynamicArchive(archive, generatedDynamicArchive)
            generatedDynamicArchive.delete()
        }
        val result = Result(
            archive = archive,
            requestedExplicitMappings = mappings.size,
            convertedExplicitMappings = explicitConverted,
            fallbackCandidates = fallbackCandidates,
            convertedFallbackMappings = fallbackConverted,
            convertedPackageDefaults = packageDefaultsConverted,
            nativeMonochromeIcons = nativeMonochromeIcons,
            skippedMappings = skipped,
            archiveSha256 = sha256(archive),
            dynamicArchive = null,
        )
        if (monetCompatibilityRenders > 0 || monetEmergencyFallbacks > 0) {
            Log.w(
                "HyperIconPack",
                "Monet renderer compatibility path: simplified=$monetCompatibilityRenders, emergency=$monetEmergencyFallbacks",
            )
        }
        onProgress?.invoke(
            ConversionProgress(
                phase = ConversionPhase.COMPLETED,
                completed = progressTotal,
                total = progressTotal,
                explicitCompleted = mappings.size,
                explicitTotal = mappings.size,
                fallbackCompleted = fallbackWorkTotal,
                fallbackTotal = fallbackWorkTotal,
            ),
        )
        return result
    }

    /**
     * Looks up the durable cache for one exact pack/scale combination. A
     * matching legacy archive is recognised as a one-time migration path.
     */
    fun existingArchive(
        context: Context,
        iconPackPackage: String?,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean = false,
        monetCustomColors: Boolean = false,
        monetBackgroundColor: Int = IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
        monetForegroundColor: Int = IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
    ): File? {
        val packageName = iconPackPackage?.takeIf(String::isNotBlank) ?: return null
        val scopeFingerprint = applicationScopeFingerprint(context)
        val cached = archiveFile(
            context = context,
            iconPackPackage = packageName,
            fallbackScaleMultiplier = fallbackScaleMultiplier,
            globalMonetIcons = globalMonetIcons,
            monetCustomColors = monetCustomColors,
            monetBackgroundColor = monetBackgroundColor,
            monetForegroundColor = monetForegroundColor,
            applicationScopeFingerprint = scopeFingerprint,
            createDirectory = false,
        )
            .takeIf(File::isFile)
        if (cached != null && readArchiveInfo(cached)?.isCurrentFormat == true) return cached

        val legacy = legacyArchive(context).takeIf(File::isFile) ?: return null
        val info = readArchiveInfo(legacy)
        return legacy.takeIf {
                info?.isCurrentFormat == true &&
                info.iconPackPackage == packageName &&
                info.fallbackScaleMultiplier?.let { scale -> kotlin.math.abs(scale - fallbackScaleMultiplier) < 0.001f } == true &&
                info.globalMonetIcons == globalMonetIcons &&
                info.monetCustomColors == (globalMonetIcons && monetCustomColors) &&
                (!globalMonetIcons || !monetCustomColors ||
                    (info.monetBackgroundColor == monetBackgroundColor &&
                        info.monetForegroundColor == monetForegroundColor)) &&
                info.applicationScopeFingerprint == scopeFingerprint
        }
    }

    /**
     * Reads only the small metadata entry written by [convert].  Older
     * archives deliberately remain usable; they are reported with null
     * metadata instead of being mistaken for an absent conversion.
     */
    fun existingArchiveInfo(
        context: Context,
        iconPackPackage: String?,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean = false,
        monetCustomColors: Boolean = false,
        monetBackgroundColor: Int = IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
        monetForegroundColor: Int = IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
    ): ExistingArchiveInfo? = existingArchive(
        context = context,
        iconPackPackage = iconPackPackage,
        fallbackScaleMultiplier = fallbackScaleMultiplier,
        globalMonetIcons = globalMonetIcons,
        monetCustomColors = monetCustomColors,
        monetBackgroundColor = monetBackgroundColor,
        monetForegroundColor = monetForegroundColor,
    )
        ?.let(::readArchiveInfo)

    /** Reads metadata for the exact durable archive selected by the user. */
    fun archiveInfo(archive: File?): ExistingArchiveInfo? = archive
        ?.takeIf(File::isFile)
        ?.let(::readArchiveInfo)

    /**
     * Adds/replaces just one installed package in an already validated static
     * archive. This is intentionally not a second full conversion: all of an
     * icon pack's explicit appfilter mappings are copied verbatim and only the
     * new app's package default plus its launcher aliases are rendered.
     *
     * The resulting archive uses the new installed-package fingerprint and is
     * installed by [PackageThemeArchiveUpdateReceiver] after PACKAGE_ADDED.
     */
    internal fun updateInstalledPackage(
        context: Context,
        baseArchive: File,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean,
        monetCustomColors: Boolean,
        monetBackgroundColor: Int,
        monetForegroundColor: Int,
        packageName: String,
    ): File = updateInstalledPackages(
        context = context,
        baseArchive = baseArchive,
        iconPackPackage = iconPackPackage,
        fallbackScaleMultiplier = fallbackScaleMultiplier,
        globalMonetIcons = globalMonetIcons,
        monetCustomColors = monetCustomColors,
        monetBackgroundColor = monetBackgroundColor,
        monetForegroundColor = monetForegroundColor,
        packageNames = listOf(packageName),
    )

    /**
     * Persists a coalesced package-install batch with one icon-pack parse and
     * one ZIP rewrite. App stores commonly update several packages together;
     * rewriting and installing the complete 30-150 MB archive once per package
     * wastes I/O and can keep Launcher under storage pressure for minutes.
     */
    internal fun updateInstalledPackages(
        context: Context,
        baseArchive: File,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean,
        monetCustomColors: Boolean,
        monetBackgroundColor: Int,
        monetForegroundColor: Int,
        packageNames: Collection<String>,
    ): File {
        require(baseArchive.isFile) { "缺少当前主题归档" }
        val requestedPackages = packageNames.asSequence()
            .filter(String::isNotBlank)
            .distinct()
            .sorted()
            .toList()
        require(requestedPackages.isNotEmpty()) { "安装包名为空" }
        val baseInfo = readArchiveInfo(baseArchive)
            ?: throw IllegalStateException("当前主题归档元数据无法读取")
        require(baseInfo.isCurrentFormat) { "当前主题归档格式过旧，需要先重新转换一次" }
        require(baseInfo.iconPackPackage == iconPackPackage) { "当前主题来源与活动配置不一致" }
        require(baseInfo.globalMonetIcons == globalMonetIcons) { "当前主题 Monet 配置与活动配置不一致" }
        require(baseInfo.monetCustomColors == (globalMonetIcons && monetCustomColors)) {
            "当前主题 Monet 配色模式与活动配置不一致"
        }
        require(!globalMonetIcons || !monetCustomColors ||
            (baseInfo.monetBackgroundColor == monetBackgroundColor &&
                baseInfo.monetForegroundColor == monetForegroundColor)) {
            "当前主题 Monet 自定义配色与活动配置不一致"
        }
        require(baseInfo.fallbackScaleMultiplier?.let { kotlin.math.abs(it - fallbackScaleMultiplier) < 0.001f } == true) {
            "当前主题适配比例与活动配置不一致"
        }

        var parseFailure: Throwable? = null
        val pack = if (isOriginalIconSource(iconPackPackage)) {
            null
        } else {
            ParsedIconPack.load(context, iconPackPackage) { parseFailure = it }
                ?: throw IllegalStateException("无法读取当前图标包", parseFailure)
        }
        val palette = if (globalMonetIcons) {
            SystemMonetIconPalette.global(context, monetCustomColors, monetBackgroundColor, monetForegroundColor)
        } else {
            null
        }
        val launchEntriesByPackage = launchableActivities(context)
            .mapNotNull { info -> componentName(info)?.let { info.packageName to archiveEntryName(it) } }
            .groupBy(keySelector = { it.first }, valueTransform = { it.second })
        val replacementEntries = linkedMapOf<String, ByteArray>()

        requestedPackages.forEach { packageName ->
            val applicationInfo = context.packageManager.getApplicationInfo(
                packageName,
                PackageManager.MATCH_DISABLED_COMPONENTS,
            )
            val rawIcon = rawApplicationIcon(context, applicationInfo)
                ?: throw IllegalStateException("无法读取 $packageName 的原始图标")
            val mappedDrawable = mappedPackageDrawable(pack, packageName, prepareForMonet = globalMonetIcons)
            val preparedFallback = bestPackageDrawable(
                pack = pack,
                packageName = packageName,
                rawIcon = rawIcon,
                fallbackComponent = ComponentName(packageName, packageName),
                fallbackScaleMultiplier = fallbackScaleMultiplier,
                systemAdaptiveMask = null,
                prepareForMonet = globalMonetIcons,
            )
            val rawNativeMonochrome = if (globalMonetIcons && mappedDrawable == null) {
                nativeMonochromeSource(rawIcon)
            } else {
                null
            }
            val nativeMonochrome = rawNativeMonochrome?.let { native ->
                preparedFallback?.let { silhouette ->
                    native.copy(silhouette = silhouette, recoveryDrawable = silhouette)
                } ?: native
            }
            val styledDrawable = mappedDrawable ?: nativeMonochrome?.glyph ?: preparedFallback
                ?: throw IllegalStateException("无法构造 $packageName 的图标样式")
            val packagePng = renderIncrementalPng(styledDrawable, palette, nativeMonochrome)
                ?: throw IllegalStateException("无法渲染 $packageName 的图标")
            replacementEntries[packageArchiveEntryName(packageName)] = packagePng
            launchEntriesByPackage[packageName].orEmpty().distinct().forEach { entryName ->
                replacementEntries[entryName] = packagePng
            }
        }

        val scopeFingerprint = applicationScopeFingerprint(context)
        val destination = archiveFile(
            context = context,
            iconPackPackage = iconPackPackage,
            fallbackScaleMultiplier = fallbackScaleMultiplier,
            globalMonetIcons = globalMonetIcons,
            monetCustomColors = monetCustomColors,
            monetBackgroundColor = monetBackgroundColor,
            monetForegroundColor = monetForegroundColor,
            applicationScopeFingerprint = scopeFingerprint,
            createDirectory = true,
        )
        val temporary = File(destination.parentFile, "${destination.name}.package-update")
        try {
            ZipFile(baseArchive).use { input ->
                ZipOutputStream(BufferedOutputStream(FileOutputStream(temporary))).use { output ->
                    output.setLevel(Deflater.NO_COMPRESSION)
                    writeArchiveMetadata(
                        zip = output,
                        iconPackPackage = iconPackPackage,
                        fallbackScaleMultiplier = fallbackScaleMultiplier,
                        globalMonetIcons = globalMonetIcons,
                        monetCustomColors = monetCustomColors,
                        monetBackgroundColor = monetBackgroundColor,
                        monetForegroundColor = monetForegroundColor,
                        applicationScopeFingerprint = scopeFingerprint,
                    )
                    writeTransformConfig(output, useDynamicIcon = false)
                    input.entries().asSequence().forEach { entry ->
                        if (
                            entry.name == METADATA_ENTRY ||
                            entry.name == TRANSFORM_CONFIG_ENTRY ||
                            entry.name in replacementEntries
                        ) return@forEach
                        output.putNextEntry(ZipEntry(entry.name))
                        try {
                            if (!entry.isDirectory) input.getInputStream(entry).use { it.copyTo(output) }
                        } finally {
                            output.closeEntry()
                        }
                    }
                    replacementEntries.forEach { (entryName, png) ->
                        output.putNextEntry(ZipEntry(entryName))
                        try {
                            output.write(png)
                        } finally {
                            output.closeEntry()
                        }
                    }
                }
            }
            ZipFile(temporary).use { zip ->
                replacementEntries.keys.forEach { entryName ->
                    require(zip.getEntry(entryName)?.size ?: 0L > 0L) {
                        "增量主题归档校验失败：缺少 $entryName"
                    }
                }
            }
            if (destination.exists() && !destination.delete()) {
                throw IllegalStateException("无法替换旧的增量主题归档")
            }
            if (!temporary.renameTo(destination)) {
                throw IllegalStateException("无法提交增量主题归档")
            }
            val destinationDynamic = dynamicArchiveFor(destination)
            // Dynamic calendar trees are embedded in the primary icons ZIP.
            // Never carry a legacy sidecar forward: the installer deliberately
            // keeps /data/system/theme/dynamicicons out of the active lookup
            // path so Xiaomi's stock Adaptive tree cannot override pack shape.
            destinationDynamic.delete()
            return destination
        } catch (throwable: Throwable) {
            temporary.delete()
            throw throwable
        }
    }

    /**
     * Renders one installed package for the exported read-only icon provider.
     * This is the live equivalent of an incremental archive entry and uses the
     * exact same pack fallback, shape and Monet rules as offline conversion.
     */
    internal fun renderInstalledPackagePng(
        context: Context,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean,
        monetCustomColors: Boolean,
        monetBackgroundColor: Int,
        monetForegroundColor: Int,
        packageName: String,
    ): ByteArray? = runCatching {
        val applicationInfo = context.packageManager.getApplicationInfo(
            packageName,
            PackageManager.MATCH_DISABLED_COMPONENTS,
        )
        val rawIcon = rawApplicationIcon(context, applicationInfo)
            ?: throw IllegalStateException("无法读取 $packageName 的原始图标")
        val pack = if (isOriginalIconSource(iconPackPackage)) {
            null
        } else {
            ParsedIconPack.load(context, iconPackPackage)
                ?: throw IllegalStateException("无法读取当前图标包")
        }
        val mapped = mappedPackageDrawable(pack, packageName, prepareForMonet = globalMonetIcons)
        val prepared = bestPackageDrawable(
            pack = pack,
            packageName = packageName,
            rawIcon = rawIcon,
            fallbackComponent = ComponentName(packageName, packageName),
            fallbackScaleMultiplier = fallbackScaleMultiplier,
            systemAdaptiveMask = null,
            prepareForMonet = globalMonetIcons,
        ) ?: throw IllegalStateException("无法构造 $packageName 的图标样式")
        val rawNative = if (globalMonetIcons && mapped == null) nativeMonochromeSource(rawIcon) else null
        val native = rawNative?.copy(silhouette = prepared, recoveryDrawable = prepared)
        val drawable = mapped ?: native?.glyph ?: prepared
        val palette = if (globalMonetIcons) {
            SystemMonetIconPalette.global(context, monetCustomColors, monetBackgroundColor, monetForegroundColor)
        } else {
            null
        }
        renderIncrementalPng(drawable, palette, native)
    }.getOrNull()

    /** All valid cached archives, used by the settings UI for fast switching. */
    fun cachedArchiveInfos(context: Context): List<ExistingArchiveInfo> {
        val directory = archiveDirectory(context, createDirectory = false) ?: return legacyArchive(context)
            .takeIf(File::isFile)
            ?.let(::readArchiveInfo)
            ?.let(::listOf)
            .orEmpty()
        val cached = directory.listFiles { file ->
            file.isFile && file.name.startsWith(ARCHIVE_FILE_PREFIX) && file.extension == "zip"
        }.orEmpty().mapNotNull(::readArchiveInfo)
        val legacy = legacyArchive(context).takeIf(File::isFile)?.let(::readArchiveInfo)
        return (cached + listOfNotNull(legacy))
            .filter(ExistingArchiveInfo::isCurrentFormat)
            .distinctBy { it.archive.absolutePath }
            .sortedWith(compareBy(String.CASE_INSENSITIVE_ORDER) { it.iconPackPackage ?: it.archive.name })
    }

    /**
     * Finds the newest valid archive for a source, regardless of the installed
     * application fingerprint embedded in its filename.  The fingerprint is
     * intentionally part of the conversion cache key, so installing or
     * removing an app can make the exact-key lookup miss even while the
     * previously applied archive is still the active system theme.
     */
    fun latestCachedArchiveForSource(
        context: Context,
        iconPackPackage: String?,
    ): ExistingArchiveInfo? {
        if (iconPackPackage.isNullOrBlank()) return null
        return cachedArchiveInfos(context)
            .asSequence()
            .filter { it.iconPackPackage == iconPackPackage }
            .maxByOrNull { it.archive.lastModified() }
    }

    /**
     * Removes only a converter-owned cache file. The active HyperOS archive
     * under /data/system/theme is intentionally untouched: deleting a cache
     * must never silently change the icon theme currently visible to the user.
     */
    fun deleteCachedArchive(context: Context, archive: File): Boolean {
        val directory = archiveDirectory(context, createDirectory = false) ?: return false
        val expectedParent = runCatching { directory.canonicalFile }.getOrNull() ?: return false
        val candidate = runCatching { archive.canonicalFile }.getOrNull() ?: return false
        if (candidate.parentFile != expectedParent) return false
        if (!candidate.name.startsWith(ARCHIVE_FILE_PREFIX) || !candidate.name.endsWith(".zip")) return false
        val deleted = !candidate.exists() || candidate.delete()
        if (deleted) dynamicArchiveFor(candidate).delete()
        return deleted
    }

    fun dynamicArchiveFor(iconArchive: File): File = File(
        iconArchive.parentFile,
        "${iconArchive.nameWithoutExtension}$DYNAMIC_ARCHIVE_SUFFIX",
    )

    /**
     * Copies only classic MAML entries into the main icons ZIP.  Keeping these
     * entries in the primary archive is intentional: when UseDynamicIcon is
     * disabled, ThemeResourcesSystem never consults the stock dynamicicons
     * archive and IconCustomizer resolves our alpha-preserving classic tree.
     */
    private fun embedClassicDynamicArchive(iconArchive: File, dynamicArchive: File) {
        val temporary = File(iconArchive.parentFile, "${iconArchive.name}.embed-dynamic.new")
        ZipFile(iconArchive).use { icons ->
            ZipFile(dynamicArchive).use { dynamic ->
                ZipOutputStream(BufferedOutputStream(FileOutputStream(temporary))).use { output ->
                    output.setLevel(Deflater.NO_COMPRESSION)
                    writeTransformConfig(output, useDynamicIcon = false)
                    val written = HashSet<String>()
                    icons.entries().asSequence().forEach { entry ->
                        if (entry.name == TRANSFORM_CONFIG_ENTRY) return@forEach
                        if (!written.add(entry.name)) return@forEach
                        output.putNextEntry(ZipEntry(entry.name))
                        try {
                            if (!entry.isDirectory) {
                                icons.getInputStream(entry).use { it.copyTo(output) }
                            }
                        } finally {
                            output.closeEntry()
                        }
                    }
                    dynamic.entries().asSequence()
                        .filter { it.name.startsWith("animating_icons/") }
                        .forEach { entry ->
                            if (!written.add(entry.name)) return@forEach
                            output.putNextEntry(ZipEntry(entry.name))
                            try {
                                if (!entry.isDirectory) {
                                    dynamic.getInputStream(entry).use { it.copyTo(output) }
                                }
                            } finally {
                                output.closeEntry()
                            }
                        }
                }
            }
        }
        if (!iconArchive.delete()) {
            temporary.delete()
            throw IllegalStateException("无法合并动态图标资源到主题归档")
        }
        if (!temporary.renameTo(iconArchive)) {
            temporary.delete()
            throw IllegalStateException("无法提交合并后的主题归档")
        }
    }

    /** Keeps the archive's dynamic lookup flag aligned with the installer. */
    fun ensureUseDynamicIconTransformConfig(
        iconArchive: File,
        enableDynamicIcons: Boolean,
    ): File {
        ZipFile(iconArchive).use { zip ->
            val existing = zip.getEntry(TRANSFORM_CONFIG_ENTRY)
            if (existing != null) {
                val content = zip.getInputStream(existing).use { it.readBytes().toString(Charsets.UTF_8) }
                val expected = enableDynamicIcons.toString()
                if (
                    content.contains("name=\"UseDynamicIcon\" value=\"$expected\"") &&
                    content.contains("name=\"SupportLayerIcon\" value=\"false\"")
                ) {
                    return iconArchive
                }
            }
        }
        val temporary = File(iconArchive.parentFile, "${iconArchive.name}.dynamic-config.new")
        ZipFile(iconArchive).use { input ->
            ZipOutputStream(BufferedOutputStream(FileOutputStream(temporary))).use { output ->
                output.setLevel(Deflater.NO_COMPRESSION)
                writeTransformConfig(output, useDynamicIcon = enableDynamicIcons)
                input.entries().asSequence().forEach { entry ->
                    if (entry.name == TRANSFORM_CONFIG_ENTRY) return@forEach
                    output.putNextEntry(ZipEntry(entry.name))
                    try {
                        if (!entry.isDirectory) {
                            input.getInputStream(entry).use { stream -> stream.copyTo(output) }
                        }
                    } finally {
                        output.closeEntry()
                    }
                }
            }
        }
        if (!iconArchive.delete()) {
            temporary.delete()
            throw IllegalStateException("无法更新主题归档的动态图标配置")
        }
        if (!temporary.renameTo(iconArchive)) {
            temporary.delete()
            throw IllegalStateException("无法提交主题归档的动态图标配置")
        }
        return iconArchive
    }

    private fun readArchiveInfo(archive: File): ExistingArchiveInfo? {
        return runCatching {
            ZipFile(archive).use { zip ->
                val entry = zip.getEntry(METADATA_ENTRY) ?: return@use ExistingArchiveInfo(
                    archive = archive,
                    iconPackPackage = null,
                    fallbackScaleMultiplier = null,
                    globalMonetIcons = false,
                    monetCustomColors = false,
                    monetBackgroundColor = IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
                    monetForegroundColor = IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
                    applicationScopeFingerprint = ALL_APPLICATIONS_SCOPE,
                    formatVersion = null,
                )
                val values = linkedMapOf<String, String>()
                zip.getInputStream(entry).bufferedReader().useLines { lines ->
                    lines.forEach { line ->
                        val divider = line.indexOf('=')
                        if (divider > 0) {
                            values[line.substring(0, divider)] = line.substring(divider + 1)
                        }
                    }
                }
                ExistingArchiveInfo(
                    archive = archive,
                    iconPackPackage = values["icon_pack_package"]?.takeIf(String::isNotBlank),
                    fallbackScaleMultiplier = values["fallback_scale"]?.toFloatOrNull(),
                    // Rendering revisions invalidate conversion caches, but
                    // older saved Monet archives remain Monet archives when
                    // reapplied or incrementally updated after an app install.
                    globalMonetIcons = values["icon_rendering"]
                        ?.startsWith(GLOBAL_MONET_RENDERING_PREFIX) == true,
                    monetCustomColors = values["monet_palette"] == "custom",
                    monetBackgroundColor = values["monet_background"]
                        ?.toLongOrNull(16)
                        ?.toInt()
                        ?: IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
                    monetForegroundColor = values["monet_foreground"]
                        ?.toLongOrNull(16)
                        ?.toInt()
                        ?: IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
                    applicationScopeFingerprint = values["application_scope"] ?: ALL_APPLICATIONS_SCOPE,
                    formatVersion = values["format"]?.toIntOrNull(),
                )
            }
        }.getOrElse {
            // The file exists and may already be installed. Do not treat a
            // malformed/legacy metadata entry as a failed conversion.
            ExistingArchiveInfo(
                archive = archive,
                iconPackPackage = null,
                fallbackScaleMultiplier = null,
                globalMonetIcons = false,
                monetCustomColors = false,
                monetBackgroundColor = IconPackConfig.DEFAULT_MONET_BACKGROUND_COLOR,
                monetForegroundColor = IconPackConfig.DEFAULT_MONET_FOREGROUND_COLOR,
                applicationScopeFingerprint = ALL_APPLICATIONS_SCOPE,
                formatVersion = null,
            )
        }
    }

    private fun archiveFile(
        context: Context,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean,
        monetCustomColors: Boolean,
        monetBackgroundColor: Int,
        monetForegroundColor: Int,
        applicationScopeFingerprint: String,
        createDirectory: Boolean,
    ): File {
        val root = context.getExternalFilesDir(ARCHIVE_DIRECTORY)
            ?: throw IllegalStateException("外部应用文件目录不可用，无法创建待应用的主题归档")
        val directory = File(root, ARCHIVE_CACHE_DIRECTORY)
        if (createDirectory) {
            ensureArchiveDirectoryWritable(directory)
        } else if (!directory.exists() && !directory.mkdirs()) {
            throw IllegalStateException("无法创建主题归档目录：${directory.absolutePath}")
        }
        // Preserve the pre-Monet identity for the ordinary converter path so
        // a user's durable v4 cache remains reusable. This global renderer
        // gets a separate identity and can never overwrite it.
        val identity = buildString {
            append("format=").append(CURRENT_FORMAT_VERSION).append('|')
            append(iconPackPackage)
            append('|').append("%.3f".format(Locale.ROOT, fallbackScaleMultiplier))
            if (globalMonetIcons) append("|render=").append(GLOBAL_MONET_RENDERING)
            if (globalMonetIcons && monetCustomColors) {
                append("|palette=custom")
                append("|background=").append(monetBackgroundColor.toUInt().toString(16))
                append("|foreground=").append(monetForegroundColor.toUInt().toString(16))
            }
            if (applicationScopeFingerprint != ALL_APPLICATIONS_SCOPE) append("|apps=").append(applicationScopeFingerprint)
        }
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(identity.toByteArray(Charsets.UTF_8))
            .joinToString("") { byte -> "%02x".format(Locale.ROOT, byte) }
        return File(directory, "$ARCHIVE_FILE_PREFIX${digest.take(20)}.zip")
    }

    fun applicationScopeFingerprint(context: Context): String {
        return packageSetFingerprint(installedApplications(context).map(ApplicationInfo::packageName))
    }

    private fun packageSetFingerprint(packages: Collection<String>): String {
        val normalized = packages.filter(String::isNotBlank).sorted()
        return MessageDigest.getInstance("SHA-256")
            .digest(normalized.joinToString("\n").toByteArray(Charsets.UTF_8))
            .joinToString("") { byte -> "%02x".format(Locale.ROOT, byte) }
            .take(SCOPE_FINGERPRINT_LENGTH)
    }


    /**
     * External archive storage lives under Android/data.  After uninstall/
     * reinstall the directory tree can remain owned by the previous app uid
     * (and an older multi-category SELinux context).  Future writes then fail
     * with EACCES even though getExternalFilesDir() returns a path.  Reclaim
     * ownership once when we cannot write.
     */
    private fun ensureArchiveDirectoryWritable(directory: File) {
        if (directory.exists() || directory.mkdirs()) {
            val probe = File(directory, ".write-probe")
            val writable = runCatching {
                probe.outputStream().use { it.write(0) }
                probe.delete()
                true
            }.getOrDefault(false)
            if (writable) return
        }

        val path = directory.absolutePath.replace("'", "'\''")
        val result = RootAccess.runFixed(
            command = """
                set -e
                path='$path'
                app_uid="${'$'}(stat -c %u /data/user/0/io.github.cl0ura.hypericonpack 2>/dev/null || true)"
                [ -n "${'$'}app_uid" ]
                mkdir -p "${'$'}path"
                # Keep the media group for FUSE visibility, but the owner must
                # match the currently installed app uid.
                chown -R "${'$'}app_uid:ext_data_rw" "${'$'}(dirname "${'$'}(dirname "${'$'}path")")" 2>/dev/null || true
                chown -R "${'$'}app_uid:ext_data_rw" "${'$'}path"
                find "${'$'}path" -type d -exec chmod 2770 {} +
                find "${'$'}path" -type f -exec chmod 660 {} +
                chcon -R u:object_r:media_rw_data_file:s0 "${'$'}path" 2>/dev/null || true
                touch "${'$'}path/.write-probe"
                chown "${'$'}app_uid:ext_data_rw" "${'$'}path/.write-probe"
                chmod 660 "${'$'}path/.write-probe"
                rm -f "${'$'}path/.write-probe"
                echo 'HYPER_ICONPACK_ARCHIVE_DIR_OK'
            """.trimIndent(),
            timeoutSeconds = 20L,
        )
        if (!result.success || !result.output.contains("HYPER_ICONPACK_ARCHIVE_DIR_OK")) {
            throw IllegalStateException(
                "主题归档目录不可写：${directory.absolutePath}. ${result.output}".trim(),
            )
        }
        if (!directory.exists() && !directory.mkdirs()) {
            throw IllegalStateException("无法创建主题归档目录：${directory.absolutePath}")
        }
        val probe = File(directory, ".write-probe")
        runCatching {
            probe.outputStream().use { it.write(0) }
            probe.delete()
        }.getOrElse {
            throw IllegalStateException(
                "主题归档目录仍不可写：${directory.absolutePath}",
                it,
            )
        }
    }

    private fun archiveDirectory(context: Context, createDirectory: Boolean): File? {
        val root = context.getExternalFilesDir(ARCHIVE_DIRECTORY) ?: return null
        val directory = File(root, ARCHIVE_CACHE_DIRECTORY)
        if (createDirectory) {
            ensureArchiveDirectoryWritable(directory)
        }
        return directory.takeIf { it.exists() || createDirectory }
    }

    private fun legacyArchive(context: Context): File {
        val directory = context.getExternalFilesDir(ARCHIVE_DIRECTORY)
            ?: return File(context.filesDir, ".no-legacy-hypericonpack-icons")
        return File(directory, ARCHIVE_FILE_NAME)
    }

    fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().buffered().use { input ->
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            while (true) {
                val count = input.read(buffer)
                if (count < 0) break
                digest.update(buffer, 0, count)
            }
        }
        return digest.digest().joinToString("") { byte -> "%02x".format(Locale.ROOT, byte) }
    }

    private fun archiveEntryName(component: ComponentName): String {
        // ZIP entry names are case-sensitive.  HyperOS passes the installed
        // package string through to IconCustomizer, and packages such as
        // com.MobileTicket / com.miHoYo.* retain capital letters.
        val packageName = component.packageName
        val className = component.className
        val iconName = if (className.startsWith(packageName)) {
            className
        } else {
            "$packageName#$className"
        }
        return "$TARGET_DENSITY_DIRECTORY/$iconName.png"
    }

    private fun packageArchiveEntryName(packageName: String): String =
        "$TARGET_DENSITY_DIRECTORY/$packageName.png"

    private fun launchableActivities(context: Context): List<ActivityInfo> {
        val launcherIntent = Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER)
        @Suppress("DEPRECATION")
        return context.packageManager.queryIntentActivities(launcherIntent, 0)
            .mapNotNull { it.activityInfo }
            .distinctBy { info -> "${info.packageName}/${info.name}" }
            .sortedWith(compareBy(ActivityInfo::packageName, ActivityInfo::name))
    }

    @Suppress("DEPRECATION")
    private fun installedApplications(context: Context): List<ApplicationInfo> =
        context.packageManager.getInstalledApplications(PackageManager.MATCH_DISABLED_COMPONENTS)
            .asSequence()
            .filter { info -> info.packageName.isNotBlank() }
            .distinctBy(ApplicationInfo::packageName)
            .sortedBy(ApplicationInfo::packageName)
            .toList()

    private fun componentName(activityInfo: ActivityInfo): ComponentName? {
        val packageName = activityInfo.packageName.takeIf(String::isNotBlank) ?: return null
        val rawClassName = activityInfo.name.takeIf(String::isNotBlank) ?: return null
        val className = if (rawClassName.startsWith('.')) packageName + rawClassName else rawClassName
        return ComponentName(packageName, className)
    }

    /**
     * This intentionally uses PackageManager#getDrawable, the same raw app
     * resource lookup IconCustomizer itself uses before applying a theme.  It
     * avoids recursively baking an already themed icon into the fallback.
     */
    private fun rawApplicationIcon(context: Context, applicationInfo: ApplicationInfo): Drawable? {
        val packageManager = context.packageManager
        val resourceId = applicationInfo.icon
        val declared = if (resourceId != 0) {
            runCatching {
                packageManager.getDrawable(applicationInfo.packageName, resourceId, applicationInfo)
            }.getOrNull()
        } else {
            null
        }
        // Split/resource-overlay packages occasionally declare an icon id
        // that PackageManager cannot resolve from the base APK. Fall through
        // to getApplicationIcon instead of dropping the package from live or
        // incremental conversion entirely.
        return declared ?: runCatching { packageManager.getApplicationIcon(applicationInfo) }.getOrNull()
    }

    /**
     * Resolves an Activity-specific icon without passing it through themed
     * icon lookup. Most launch activities inherit the application icon, but
     * a few apps deliberately define a separate adaptive icon for a shortcut
     * or entry point.
     */
    private fun rawActivityIcon(context: Context, activityInfo: ActivityInfo): Drawable? {
        val resourceId = activityInfo.icon
        return if (resourceId != 0) {
            runCatching {
                context.packageManager.getDrawable(
                    activityInfo.packageName,
                    resourceId,
                    activityInfo.applicationInfo,
                )
            }.getOrNull()
        } else {
            rawApplicationIcon(context, activityInfo.applicationInfo)
        }
    }

    /** Finds one raw AdaptiveIconDrawable whose icon mask reflects this OEM. */
    private fun resolveSystemAdaptiveMask(
        context: Context,
        applications: List<ApplicationInfo>,
    ): AdaptiveIconDrawable? {
        val packageManager = context.packageManager
        val preferredPackages = listOf("com.miui.home", "com.android.settings", "com.android.systemui")
        val preferred = preferredPackages.asSequence()
            .mapNotNull { packageName ->
                applications.firstOrNull { it.packageName == packageName }
                    ?: runCatching { packageManager.getApplicationInfo(packageName, 0) }.getOrNull()
            }
        return (preferred + applications.asSequence())
            .mapNotNull { info -> rawApplicationIcon(context, info) as? AdaptiveIconDrawable }
            .firstOrNull()
            ?.let { drawable ->
                drawable.constantState?.newDrawable()?.mutate() as? AdaptiveIconDrawable ?: drawable
            }
    }

    /**
     * Android 13 introduced [AdaptiveIconDrawable.monochrome] for launcher
     * themed icons.  Unlike a colour/luminance heuristic, this layer is an
     * application-provided semantic glyph and is therefore the most faithful
     * possible source for Monet.  Its original AdaptiveIconDrawable is kept
     * as the shape source, so the converter does not force a circular frame.
     * The API guard keeps the converter compatible with older Android
     * versions.
     */
    private fun nativeMonochromeSource(drawable: Drawable?): NativeMonochromeSource? {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return null
        val adaptiveIcon = drawable as? AdaptiveIconDrawable ?: return null
        val monochrome = adaptiveIcon.monochrome ?: return null
        val glyph = monochrome.constantState?.newDrawable()?.mutate() ?: monochrome.mutate()
        val rawSilhouette = adaptiveIcon.constantState?.newDrawable()?.mutate() ?: adaptiveIcon.mutate()
        // `AdaptiveIconDrawable#draw` is permitted to paint its background
        // across the whole temporary canvas.  In the normal launcher pipeline
        // an adaptive mask is applied afterwards, but a static PNG has no
        // such later stage.  Always bake that mask now; otherwise just turning
        // on Global Monet can make a circular icon-pack fallback become a
        // square coloured tile.
        val silhouette = SystemIconShapeDrawable(
            source = rawSilhouette,
            systemMask = null,
        )
        return NativeMonochromeSource(
            glyph = glyph,
            silhouette = silhouette,
            recoveryDrawable = rawSilhouette,
        )
    }

    /**
     * Chooses the exact appfilter mapping when one is usable; otherwise bakes
     * the public iconback/mask/upon fallback once into the archive.  This is
     * intentionally converter-only: no live launcher or SystemUI Drawable is
     * replaced at runtime.
     */
    private fun bestPackageDrawable(
        pack: ParsedIconPack?,
        packageName: String,
        rawIcon: Drawable?,
        fallbackComponent: ComponentName,
        fallbackScaleMultiplier: Float,
        systemAdaptiveMask: AdaptiveIconDrawable?,
        prepareForMonet: Boolean = false,
    ): Drawable? {
        fun systemShapedRawIcon(): Drawable? = rawIcon?.let { source ->
            SystemIconShapeDrawable(source = source, systemMask = systemAdaptiveMask)
        }
        if (pack == null) return systemShapedRawIcon()
        val explicit = mappedPackageDrawable(pack, packageName, prepareForMonet)
        if (explicit != null) return explicit
        if (rawIcon == null) return null
        // A lack of iconback/iconmask must never remove an installed system
        // application from the archive. Keep its raw icon as a generic
        // fallback; the global Monet renderer will still normalise it when
        // enabled, while normal mode at least remains functionally complete.
        if (!pack.supportsFallbackStyle) return systemShapedRawIcon()
        return pack.createFallback(
            original = rawIcon,
            component = fallbackComponent,
            scaleMultiplier = fallbackScaleMultiplier,
        ) ?: systemShapedRawIcon()
    }

    /** Returns a usable appfilter asset for an installed package, if any. */
    private fun mappedPackageDrawable(
        pack: ParsedIconPack?,
        packageName: String,
        prepareForMonet: Boolean = false,
    ): Drawable? {
        val resolvedPack = pack ?: return null
        val component = ComponentName(packageName, packageName)
        return resolvedPack.mappedDrawableNamesForPackage(packageName)
            .asSequence()
            .mapNotNull { drawableName ->
                if (prepareForMonet) {
                    resolvedPack.loadMappedDrawableForMonet(drawableName, component)
                } else {
                    resolvedPack.loadMappedDrawable(drawableName)
                }
            }
            .firstOrNull()
    }

    /** Converts standard appfilter calendar prefixes into HyperOS MAML dynamic icons. */
    private fun generateDynamicCalendarArchive(
        pack: ParsedIconPack?,
        installedPackageNames: Set<String>,
        launchableActivities: List<ActivityInfo>,
        iconArchive: File,
        globalMonetPalette: GlobalMonetPalette?,
        fallbackScaleMultiplier: Float,
    ): File? {
        val resolvedPack = pack ?: return null
        // HyperOS resolves dynamic icons through IconCustomizer.getIconNames():
        // activity class first (e.g. com.android.calendar.homepage.AllInOneActivity),
        // then package fallback. Emitting only the package root makes the desktop
        // miss the pack's dynamic tree and fall back to the stock square MAML icon.
        val installedMappings = resolvedPack.calendarMappings()
            .filter { it.component.packageName in installedPackageNames }
        if (installedMappings.isEmpty()) {
            dynamicArchiveFor(iconArchive).delete()
            return null
        }
        val launchableByPackage = launchableActivities
            .mapNotNull { info -> componentName(info) }
            .groupBy({ it.packageName }, { it })
        val destination = dynamicArchiveFor(iconArchive)
        val temporary = File(destination.parentFile, "${destination.name}.new")
        var convertedTrees = 0
        try {
            ZipOutputStream(BufferedOutputStream(FileOutputStream(temporary))).use { zip ->
                zip.setLevel(Deflater.NO_COMPRESSION)
                val renderedByPrefix = HashMap<String, List<ByteArray>>()
                val writtenRoots = HashSet<String>()
                installedMappings
                    .groupBy { it.component.packageName to it.drawablePrefix }
                    .forEach { (packageAndPrefix, mappings) ->
                        val (packageName, drawablePrefix) = packageAndPrefix
                        val renderedDays = renderedByPrefix.getOrPut(drawablePrefix) {
                            val frames = (1..31).map { day ->
                                val drawable = resolvedPack.loadCalendarDrawable(
                                    drawablePrefix = drawablePrefix,
                                    dayOfMonth = day,
                                    scaleMultiplier = fallbackScaleMultiplier,
                                ) ?: return@map null
                                // Reuse the exact static Monet/original pipeline so
                                // dynamic calendar frames keep the same shape and palette.
                                renderIncrementalPng(
                                    drawable = drawable,
                                    palette = globalMonetPalette,
                                    nativeMonochrome = null,
                                )
                            }
                            if (frames.any { it == null }) {
                                emptyList()
                            } else {
                                frames.filterNotNull()
                            }
                        }
                        if (renderedDays.size != 31) return@forEach
                        val relativeNames = LinkedHashSet<String>()
                        relativeNames += packageName
                        mappings.forEach { mapping ->
                            relativeNames += dynamicIconLookupName(
                                packageName = mapping.component.packageName,
                                className = mapping.component.className,
                            )
                        }
                        launchableByPackage[packageName].orEmpty().forEach { component ->
                            relativeNames += dynamicIconLookupName(
                                packageName = component.packageName,
                                className = component.className,
                            )
                        }
                        val currentDay = Calendar.getInstance()
                            .get(Calendar.DAY_OF_MONTH)
                            .coerceIn(1, 31)
                        val quiet = renderedDays[currentDay - 1]
                        val manifest = dynamicCalendarManifest()
                        relativeNames.forEach { relativeName ->
                            if (!writtenRoots.add(relativeName)) return@forEach
                            // Keep the finished PNGs on the classic path.  They
                            // retain the icon pack's own alpha shape, while the
                            // main icons archive (rather than dynamicicons) makes
                            // this path win over the stock Adaptive resources.
                            val packageRoot = "animating_icons/$relativeName"
                            appendZipText(zip, "$packageRoot/fancy/manifest.xml", manifest)
                            renderedDays.forEachIndexed { index, bytes ->
                                appendZipBytes(
                                    zip,
                                    "$packageRoot/fancy/day_${index + 1}.png",
                                    bytes,
                                )
                            }
                            appendZipBytes(zip, "$packageRoot/quiet/quietImage.png", quiet)
                            convertedTrees++
                        }
                    }
            }
            if (convertedTrees == 0) {
                temporary.delete()
                destination.delete()
                return null
            }
            ZipFile(temporary).use { zip ->
                require(zip.entries().asSequence().any { it.name.endsWith("/fancy/manifest.xml") }) {
                    "HyperOS 动态日历归档校验失败"
                }
            }
            if (destination.exists() && !destination.delete()) {
                throw IllegalStateException("无法替换旧的动态日历归档")
            }
            if (!temporary.renameTo(destination)) {
                throw IllegalStateException("无法提交动态日历归档")
            }
            return destination
        } catch (throwable: Throwable) {
            temporary.delete()
            throw throwable
        }
    }

    /**
     * Mirrors IconCustomizer.getFileName()/getIconNames() so dynamic trees are
     * discoverable for both package-level and activity-level lookups.
     */
    private fun dynamicIconLookupName(packageName: String, className: String?): String {
        val resolvedClass = className?.takeIf { it.isNotBlank() } ?: return packageName
        return if (resolvedClass.startsWith(packageName)) {
            resolvedClass
        } else {
            "$packageName#$resolvedClass"
        }
    }

    private fun appendZipText(zip: ZipOutputStream, name: String, value: String) =
        appendZipBytes(zip, name, value.toByteArray(Charsets.UTF_8))

    private fun appendZipBytes(zip: ZipOutputStream, name: String, value: ByteArray) {
        zip.putNextEntry(ZipEntry(name))
        try {
            zip.write(value)
        } finally {
            zip.closeEntry()
        }
    }

    private fun dynamicCalendarConfig(): String = """
        <Config>
            <Variables>
                <Variable name="layer0" value="0" type="string" />
                <Variable name="layer_only_fancy0" value="false" type="string" />
                <Variable name="layer_only_quiet0" value="false" type="string" />
            </Variables>
        </Config>
    """.trimIndent()

    private fun dynamicCalendarManifest(): String = """
        <?xml version="1.0" encoding="utf-8"?>
        <Icon version="1" frameRate="0" width="$DYNAMIC_ICON_SIZE_PX" height="$DYNAMIC_ICON_SIZE_PX" screenWidth="1080" useVariableUpdater="DateTime.Day">
            <ExternalCommands>
                <Trigger action="resume">
                    <FrameRateCommand rate="5" />
                    <FrameRateCommand rate="0" delay="10" />
                </Trigger>
                <Trigger action="back_home_start"><FrameRateCommand rate="60" /></Trigger>
                <Trigger action="back_home_finish"><FrameRateCommand rate="0" delay="1000" /></Trigger>
            </ExternalCommands>
            <Image x="$DYNAMIC_ICON_SIZE_PX/2" y="$DYNAMIC_ICON_SIZE_PX/2" align="center" alignV="center" src="day.png" srcid="#date" />
        </Icon>
    """.trimIndent()

    private fun renderDrawableAsPng(
        drawable: Drawable,
        output: OutputStream,
        size: Int = RENDER_SIZE_PX,
    ) {
        val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        val oldBounds = Rect(drawable.bounds)
        try {
            drawable.setBounds(0, 0, size, size)
            drawable.draw(canvas)
            if (!bitmap.compress(Bitmap.CompressFormat.PNG, 100, output)) {
                throw IllegalStateException("PNG 编码失败")
            }
        } finally {
            drawable.bounds = oldBounds
            bitmap.recycle()
        }
    }

    private fun renderIncrementalPng(
        drawable: Drawable,
        palette: GlobalMonetPalette?,
        nativeMonochrome: NativeMonochromeSource? = null,
    ): ByteArray? = runCatching {
        ByteArrayOutputStream().use { output ->
            if (palette == null) {
                renderDrawableAsPng(drawable, output)
            } else {
                val rendered = runCatching {
                    if (nativeMonochrome != null) {
                        GlobalMonetIconRenderer.renderNativeMonochrome(
                            glyph = nativeMonochrome.glyph,
                            silhouette = nativeMonochrome.silhouette,
                            palette = palette,
                            size = RENDER_SIZE_PX,
                            output = output,
                        )
                    } else {
                        GlobalMonetIconRenderer.render(
                            drawable = drawable,
                            palette = palette,
                            size = RENDER_SIZE_PX,
                            output = output,
                        )
                    }
                }.isSuccess || run {
                    output.reset()
                    runCatching {
                        GlobalMonetIconRenderer.renderSimplified(
                            drawable = nativeMonochrome?.recoveryDrawable ?: drawable,
                            palette = palette,
                            size = RENDER_SIZE_PX,
                            output = output,
                        )
                    }.isSuccess
                }
                if (!rendered) {
                    output.reset()
                    val guaranteed = runCatching {
                        GlobalMonetIconRenderer.renderGuaranteed(
                            drawable = nativeMonochrome?.recoveryDrawable ?: drawable,
                            palette = palette,
                            size = RENDER_SIZE_PX,
                            output = output,
                        )
                    }.isSuccess
                    if (!guaranteed) {
                        return@use null
                    }
                }
            }
            output.toByteArray().takeIf { it.isNotEmpty() }
        }
    }.getOrNull()

    /**
     * HyperOS only consults /data/system/theme/dynamicicons when the icons
     * archive declares UseDynamicIcon=true. Without this entry, calendar MAML
     * resources are installed but never loaded by IconCustomizer.
     */
    private fun writeTransformConfig(zip: ZipOutputStream, useDynamicIcon: Boolean) {
        // LayerAdaptiveIconDrawable treats a transparent adaptive background as
        // an opaque black canvas on the tested HyperOS 3 launcher. Keep layer
        // lookup disabled so every surface consumes the same alpha-preserving
        // main PNG; this also prevents partial fallback to stock adaptive icons
        // when a theme archive has no complete layer set.
        // Classic MAML entries embedded in the main icons archive must keep
        // UseDynamicIcon=false; otherwise the stock dynamicicons layer is
        // consulted first and AdaptiveIconDrawable re-masks pack shapes.
        val config = """
            <?xml version="1.0" encoding="UTF-8"?>
            <IconTransform>
                <Config name="SupportLayerIcon" value="false" />
                <Config name="UseDynamicIcon" value="$useDynamicIcon" />
                <Config name="ConfigIconMask" value="M0 0H100V100H0Z" />
            </IconTransform>
        """.trimIndent()
        zip.putNextEntry(ZipEntry(TRANSFORM_CONFIG_ENTRY))
        try {
            zip.write(config.toByteArray(Charsets.UTF_8))
        } finally {
            zip.closeEntry()
        }
    }

    private fun writeArchiveMetadata(
        zip: ZipOutputStream,
        iconPackPackage: String,
        fallbackScaleMultiplier: Float,
        globalMonetIcons: Boolean,
        monetCustomColors: Boolean,
        monetBackgroundColor: Int,
        monetForegroundColor: Int,
        applicationScopeFingerprint: String,
    ) {
        val metadata = buildString {
            append("format=").append(CURRENT_FORMAT_VERSION).append('\n')
            append("icon_pack_package=").append(iconPackPackage).append('\n')
            append("fallback_scale=").append(fallbackScaleMultiplier).append('\n')
            append("icon_rendering=")
                .append(if (globalMonetIcons) GLOBAL_MONET_RENDERING else DEFAULT_RENDERING)
                .append('\n')
            append("monet_palette=")
                .append(if (globalMonetIcons && monetCustomColors) "custom" else "system")
                .append('\n')
            append("monet_background=").append(monetBackgroundColor.toUInt().toString(16)).append('\n')
            append("monet_foreground=").append(monetForegroundColor.toUInt().toString(16)).append('\n')
            append("application_scope=").append(applicationScopeFingerprint).append('\n')
        }
        zip.putNextEntry(ZipEntry(METADATA_ENTRY))
        try {
            zip.write(metadata.toByteArray(Charsets.UTF_8))
        } finally {
            zip.closeEntry()
        }
    }

    private fun validateArchive(file: File, expectedIconEntries: Int) {
        ZipFile(file).use { zip ->
            val iconEntries = zip.entries().asSequence()
                .count { entry -> !entry.isDirectory && entry.name.startsWith("$TARGET_DENSITY_DIRECTORY/") && entry.name.endsWith(".png") }
            require(iconEntries == expectedIconEntries) {
                "主题归档校验失败：期望 $expectedIconEntries 个图标，实际 $iconEntries 个"
            }
            require(zip.getEntry(TRANSFORM_CONFIG_ENTRY) != null) {
                "主题归档校验失败：缺少 $TRANSFORM_CONFIG_ENTRY"
            }
        }
    }

    private fun reportProgress(
        callback: ((ConversionProgress) -> Unit)?,
        phase: ConversionPhase,
        phaseCompleted: Int,
        phaseTotal: Int,
        totalCompleted: Int,
        total: Int,
        explicitCompleted: Int,
        explicitTotal: Int,
        fallbackCompleted: Int,
        fallbackTotal: Int,
        force: Boolean = false,
    ) {
        if (callback == null || (!force && phaseCompleted % PROGRESS_REPORT_INTERVAL != 0)) return
        callback(
            ConversionProgress(
                phase = phase,
                completed = totalCompleted,
                total = total,
                explicitCompleted = explicitCompleted,
                explicitTotal = explicitTotal,
                fallbackCompleted = fallbackCompleted,
                fallbackTotal = fallbackTotal,
            ),
        )
    }
}
